[v1.0.0] Basic JWT Authentication
Gig-Client/gig-api pull request #3
Opened 2023-04-10 17:56 UTC by DaFonsecaDamien

![][trello.png] [**Création de l'authentification basique**](https://trello.com/c/nhNHlZOW/1-10-v100-cr%C3%A9ation-de-lauthentification-basique-9)
![][trello.png] [**Initialisation de l'architecture**](https://trello.com/c/ZFZ40eRh/2-3-v100-initialisation-de-larchitecture-2)

# Description

- Adding basic authentication on the application with passport and Bcrypt and initializing the architecture and the first entities, controllers, services and modules. 
- Adding API versionning and Cors.
- Added some changes in the architecture of the application in a way to manage the configuration.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

[trello.png]: https://github.trello.services/images/mini-trello-icon.png

2023-04-10 17:57 UTC, Milutin-Stan approved these changes

2023-04-11 20:37 UTC, AdrienRoux requested changes
- Run le `reformat code`
- Petits changements mineurs typos

2023-04-11 20:37 UTC, AdrienRoux commented on src/domain/services/auth/auth.service.ts
> +        }else{
```suggestion
        } else {
```

2023-04-11 20:46 UTC, AdrienRoux approved these changes
👍🏼

2023-04-11 20:48 UTC, merged