[V1.0.0] Roles and RoleGuard
Gig-Client/gig-api pull request #5
Opened 2023-04-19 14:51 UTC by Milutin-Stan

![][trello.png] [**[v1.0.0] Mettre en place les rôles (Admin Extra Employeur)**](https://trello.com/c/84bNoN4O/13-v100-mettre-en-place-les-r%C3%B4les-admin-extra-employeur)

# Description

Added roles (Admin, Extra and Employeur) with updated services and tests.
A new RoleGuard was created to protect routes for the corresponding roles (The RoleGuard also uses AuthGuard within it so that you dont need to use both).
The coverage config was also changed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

[trello.png]: https://github.trello.services/images/mini-trello-icon.png

2023-04-22 14:11 UTC, DaFonsecaDamien requested changes
Réaliser les changements demandés dans les commentaires avant le merge.

2023-04-22 14:11 UTC, DaFonsecaDamien commented on src/domain/utils/enums/role.enum.ts
Mettre les champs en Anglais

2023-04-22 14:11 UTC, DaFonsecaDamien commented on src/domain/services/role/role.service.ts
Ajouter une méthode pour permettre la suppression d'un role en base

2023-04-22 14:11 UTC, DaFonsecaDamien commented on src/application/user/user.controller.ts
Séparer la logique de vérification de l'authentification et du rôle.
Entre autre mettre l'annotation (@JWTGuard  ou autre nom) puis celle du rôle, afin que le rôle Guard fasse une et unique chose.

2023-04-22 14:11 UTC, DaFonsecaDamien commented on src/domain/guards/role.guard.ts
Laisser le RolesGuard tester uniquement les rôles et non pas l'authentification.

2023-04-22 18:26 UTC, DaFonsecaDamien approved these changes
Nice work 👍🏼

2023-04-25 07:19 UTC, AdrienRoux requested changes
Minor change

2023-04-25 07:19 UTC, AdrienRoux commented on src/domain/utils/enums/role.enum.ts
> +  EMPLOYEUR = "EMPLOYEUR",
```suggestion
  EMPLOYEUR = "EMPLOYER",
```

2023-04-25 08:43 UTC, AdrienRoux approved these changes
Fine for me ! :)

2023-04-25 08:44 UTC, merged